name: Python CICD

on:
  push:
    branches: [ cicd-pr]
  pull_request:
    branches: [ cicd-pr ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
    - uses: actions/checkout@v4
    # setup python
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    # install dependencies
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: print python version
      run: python --version
    - name: print pip version
      run: pip --version
      
    # install pytest
    - name: install pytest
      run: pip install pytest
      
    # run tests
    - name: run tests
      run: pytest test_hello.py -v
      
    # run application
    - name: run application
      run: python hello.py World
